/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 小程序登录换取会话（code2Session + 颁发 JWT） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description wx.login() 获得的临时登录凭证 */
                        code: string;
                        iv?: string | null;
                        encryptedData?: string | null;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthToken"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        /** 更新当前用户资料与同意记录 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列表查询内容（视频/3D/AR/闯关） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    type?: components["schemas"]["ContentType"];
                    step?: string;
                    tag?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paginated"] & {
                            items?: components["schemas"]["Content"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单条内容详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Content"];
                    };
                };
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品列表（SPU 维度） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    q?: string;
                    tag?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paginated"] & {
                            items?: components["schemas"]["Product"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品详情（含 SKU） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的订单列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    status?: components["schemas"]["OrderStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paginated"] & {
                            items?: components["schemas"]["Order"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建订单（未支付） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderCreate"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/jsapi_prepay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 微信支付 JSAPI 预下单，返回 wx.requestPayment 所需字段 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        orderId: string;
                        /** @description 付款人 openid */
                        payerOpenId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            timeStamp: string;
                            nonceStr: string;
                            /** @description prepay_id=xxx */
                            package: string;
                            /** @enum {string} */
                            signType: "RSA" | "HMAC-SHA256";
                            paySign: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 微信支付回调（v3），平台签名验签 + 解密资源体 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WxpayNotifyBody"];
                };
            };
            responses: {
                /** @description 必须返回 200 以告知接收成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example SUCCESS */
                            code?: string;
                            /** @example OK */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trace/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 一物一码/批次溯源查询（链上摘要 + 线下质检） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TraceBatch"];
                    };
                };
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trace/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 写入溯源事件（B 端/内部运营） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TraceEventWrite"];
                };
            };
            responses: {
                /** @description 已写入 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TraceEvent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/poi/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 附近门店/点位（LBS 导流） */
        get: {
            parameters: {
                query: {
                    lat: number;
                    lng: number;
                    radius?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["POI"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的预约列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paginated"] & {
                            items?: components["schemas"]["Booking"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建预约（研学/导览） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookingCreate"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 预约详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改预约状态（取消/确认） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status?: components["schemas"]["BookingStatus"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/moderation/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 文本内容安全审核封装（调用微信内容安全后端） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModerationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拉取当前可用实验与变体（用于灰度/AB） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            experiments?: components["schemas"]["Experiment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上报埋点事件（可并发/批量） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        events: components["schemas"]["AnalyticsEvent"][];
                    };
                };
            };
            responses: {
                /** @description 已接收 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example ERR_NOT_FOUND */
            code?: string;
            message?: string;
            requestId?: string;
        };
        AuthToken: {
            /** @description JWT */
            token?: string;
            openid?: string;
            unionid?: string | null;
            /** @example 7200 */
            expiresIn?: number;
        };
        User: {
            id?: string;
            openid?: string;
            unionid?: string | null;
            profile?: {
                nickname?: string;
                /** Format: uri */
                avatar?: string;
                /** @enum {string} */
                gender?: "male" | "female" | "unknown";
                city?: string;
                /** Format: date */
                birthday?: string | null;
            };
            tags?: string[];
            consents?: {
                privacy?: boolean;
                marketing?: boolean;
            };
            /** @default 0 */
            level: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UserUpdate: {
            profile?: components["schemas"]["User"]["profile"];
            consents?: components["schemas"]["User"]["consents"];
            tags?: string[];
        };
        /** @enum {string} */
        ContentType: "video" | "gltf" | "ar" | "quiz";
        Content: {
            id?: string;
            type?: components["schemas"]["ContentType"];
            title?: string;
            slug?: string;
            /** @description 工序编号（用于 3D/视频映射） */
            step?: string;
            vodId?: string | null;
            /** Format: uri */
            gltfUrl?: string | null;
            /** @description 秒 */
            duration?: number;
            /** Format: uri */
            cover?: string;
            tags?: string[];
            relation?: {
                artisanId?: string | null;
                productIds?: string[];
            };
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        ProductStatus: "active" | "inactive" | "archived";
        SKU: {
            skuId?: string;
            attrs?: {
                [key: string]: string;
            };
            /** @description 单位：分 */
            price?: number;
            stock?: number;
            barcode?: string | null;
        };
        Product: {
            id?: string;
            title?: string;
            subtitle?: string;
            images?: string[];
            status?: components["schemas"]["ProductStatus"];
            tags?: string[];
            descHtml?: string;
            skus?: components["schemas"]["SKU"][];
            traceCodePrefix?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        OrderStatus: "pending" | "unpaid" | "paid" | "canceled" | "fulfilled" | "refunded";
        OrderItem: {
            skuId?: string;
            qty?: number;
            title?: string;
            /** @description 单价（分） */
            price?: number;
            /** @description 小计（分） */
            amount?: number;
        };
        Order: {
            id?: string;
            userId?: string;
            items?: components["schemas"]["OrderItem"][];
            amounts?: {
                goods?: number;
                freight?: number;
                discount?: number;
                payable?: number;
            };
            status?: components["schemas"]["OrderStatus"];
            pay?: {
                outTradeNo?: string;
                prepayId?: string | null;
                transactionId?: string | null;
                payerOpenId?: string | null;
            };
            address?: {
                name?: string;
                phone?: string;
                detail?: string;
                province?: string;
                city?: string;
                district?: string;
            };
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OrderCreate: {
            items: {
                skuId: string;
                qty: number;
            }[];
            address: components["schemas"]["Order"]["address"];
            couponCode?: string | null;
        };
        WxpayNotifyBody: {
            id?: string;
            /** Format: date-time */
            create_time?: string;
            resource_type?: string;
            event_type?: string;
            summary?: string;
            resource?: {
                algorithm?: string;
                ciphertext?: string;
                associated_data?: string;
                nonce?: string;
            };
        };
        TraceEvent: {
            id?: string;
            batchId?: string;
            step?: string;
            operator?: string;
            /** Format: date-time */
            ts?: string;
            hash?: string;
            tbaasTxId?: string;
        };
        TraceEventWrite: {
            batchId: string;
            /** @example S06_drying */
            step: string;
            operator: string;
            /** Format: date-time */
            ts: string;
            hash: string;
        };
        TraceBatch: {
            batchId?: string;
            grain?: {
                origin?: string;
                /** Format: date */
                harvestDate?: string;
            };
            processSteps?: components["schemas"]["TraceEvent"][];
            qcReports?: {
                reportId?: string;
                /** Format: uri */
                url?: string;
                passed?: boolean;
            }[];
            /** @enum {string} */
            status?: "normal" | "alert" | "recalled";
        };
        POI: {
            id?: string;
            name?: string;
            address?: string;
            location?: {
                lat?: number;
                lng?: number;
            };
            openingHours?: string;
            phone?: string | null;
            /** @description 米 */
            distance?: number;
        };
        /** @enum {string} */
        BookingStatus: "pending" | "confirmed" | "canceled" | "completed";
        Booking: {
            id?: string;
            userId?: string;
            poiId?: string;
            /** Format: date */
            date?: string;
            /** @example 14:00 */
            time?: string;
            pax?: number;
            status?: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt?: string;
        };
        BookingCreate: {
            poiId: string;
            /** Format: date */
            date: string;
            time: string;
            pax: number;
        };
        ModerationResult: {
            ok?: boolean;
            /** @enum {string} */
            suggestion?: "pass" | "review" | "block";
            labels?: string[];
            reason?: string;
        };
        Experiment: {
            id?: string;
            /** @example home_layout_ab */
            key?: string;
            /** @example B */
            variant?: string;
            params?: {
                [key: string]: unknown;
            };
        };
        AnalyticsEvent: {
            /** @enum {string} */
            name: "content_view" | "ar_start" | "add_to_cart" | "purchase" | "trace_view" | "booking_submit";
            /** Format: date-time */
            ts: string;
            props?: {
                [key: string]: unknown;
            };
        };
        Paginated: {
            page?: number;
            size?: number;
            total?: number;
        };
    };
    responses: {
        /** @description 未授权 */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未找到 */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 冲突/幂等冲突 */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
